# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("gradebook", "0002_auto_20150612_1507")]

    operations = [
        migrations.AlterOrderWithRespectTo(name="bin", order_with_respect_to=None)
    ]
