# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("gradebook", "0003_auto_20151221_1217")]

    operations = [
        migrations.RemoveField(model_name="bin", name="rule"),
        migrations.RemoveField(model_name="binrule", name="rule_ptr"),
        migrations.RemoveField(model_name="binrule", name="task"),
        migrations.RemoveField(model_name="computedscoredtask", name="scored_task_ptr"),
        migrations.AlterUniqueTogether(name="delegation", unique_together=set([])),
        migrations.RemoveField(model_name="delegation", name="perms"),
        migrations.RemoveField(model_name="delegation", name="section"),
        migrations.RemoveField(model_name="droprule", name="category"),
        migrations.RemoveField(model_name="droprule", name="rule_ptr"),
        migrations.AlterUniqueTogether(name="grade_category", unique_together=set([])),
        migrations.RemoveField(model_name="grade_category", name="Section"),
        migrations.RemoveField(model_name="grade_category", name="Type"),
        migrations.RemoveField(model_name="iclicker_primitive", name="Instance"),
        migrations.AlterUniqueTogether(
            name="lettergradecutoff", unique_together=set([])
        ),
        migrations.RemoveField(model_name="lettergradecutoff", name="grade"),
        migrations.RemoveField(model_name="lettergradecutoff", name="parent"),
        migrations.RemoveField(model_name="lettergradeforsection", name="section"),
        migrations.RemoveField(model_name="lettergradeforsection", name="task"),
        migrations.AlterUniqueTogether(
            name="lettergradeforstudent", unique_together=set([])
        ),
        migrations.RemoveField(model_name="lettergradeforstudent", name="lettergrade"),
        migrations.RemoveField(model_name="lettergradeforstudent", name="section"),
        migrations.RemoveField(model_name="lettergradeforstudent", name="student"),
        migrations.RemoveField(model_name="rule", name="content_type"),
        migrations.RemoveField(model_name="rule", name="target"),
        migrations.AlterUniqueTogether(name="scored_task", unique_together=set([])),
        migrations.RemoveField(model_name="scored_task", name="Category"),
        migrations.AlterUniqueTogether(name="student_score", unique_together=set([])),
        migrations.RemoveField(model_name="student_score", name="Instance"),
        migrations.RemoveField(model_name="student_score", name="Student"),
        migrations.RemoveField(model_name="sumrule", name="category"),
        migrations.RemoveField(model_name="sumrule", name="rule_ptr"),
        migrations.RemoveField(model_name="weight", name="task"),
        migrations.RemoveField(model_name="weightrule", name="rule_ptr"),
        migrations.DeleteModel(name="Bin"),
        migrations.DeleteModel(name="BinRule"),
        migrations.DeleteModel(name="ComputedScoredTask"),
        migrations.DeleteModel(name="Delegation"),
        migrations.DeleteModel(name="DropRule"),
        migrations.DeleteModel(name="Grade_Category"),
        migrations.DeleteModel(name="Grade_Type"),
        migrations.DeleteModel(name="iclicker_primitive"),
        migrations.DeleteModel(name="LetterGrade"),
        migrations.DeleteModel(name="LetterGradeCutoff"),
        migrations.DeleteModel(name="LetterGradeForSection"),
        migrations.DeleteModel(name="LetterGradeForStudent"),
        migrations.DeleteModel(name="Permission"),
        migrations.DeleteModel(name="Rule"),
        migrations.DeleteModel(name="Scored_Task"),
        migrations.DeleteModel(name="Student_Score"),
        migrations.DeleteModel(name="SumRule"),
        migrations.DeleteModel(name="Weight"),
        migrations.DeleteModel(name="WeightRule"),
    ]
