# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 14:48
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("gradebook", "0004_auto_20160413_1543")]

    operations = [
        migrations.AlterModelOptions(
            name="task", options={"ordering": ("ordering", "category", "name")}
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                max_length=64,
                populate_from=b"name",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                help_text="The url fragment for accessing this task (must be unique for this section)",
                max_length=64,
                populate_from=b"name",
                unique_with=(b"section",),
            ),
        ),
    ]
