# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:37
from __future__ import unicode_literals

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("gradebook", "0005_auto_20170110_0848"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, max_length=128, populate_from=b"name"
                    ),
                ),
                ("ordering", models.PositiveSmallIntegerField(default=100)),
                (
                    "dtstart",
                    models.DateTimeField(
                        help_text=b"When the ledger begins", verbose_name="start"
                    ),
                ),
                (
                    "dtend",
                    models.DateTimeField(
                        help_text=b"When the ledger finishes", verbose_name="end"
                    ),
                ),
            ],
            options={"ordering": ("ordering", "name")},
        ),
        migrations.CreateModel(
            name="LedgerViewport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, max_length=128, populate_from=b"name"
                    ),
                ),
                ("ordering", models.PositiveSmallIntegerField(default=100)),
                (
                    "public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not this viewport is visible to students",
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.Ledger",
                    ),
                ),
                ("tasks", models.ManyToManyField(to="gradebook.Task")),
            ],
            options={"ordering": ("ordering", "name")},
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            (b"su", "Superuser"),
                            (b"co", "Course Coordinator"),
                            (b"in", "Instructor"),
                            (b"ta", "Teaching Assistant"),
                            (b"mk", "Marker"),
                            (b"ld", "Lab Demonstrator"),
                            (b"ob", "Observer"),
                            (b"st", "Student"),
                        ],
                        default=b"st",
                        max_length=2,
                    ),
                ),
                (
                    "dtstart",
                    models.DateTimeField(
                        help_text=b"When the role begins", verbose_name="start"
                    ),
                ),
                (
                    "dtend",
                    models.DateTimeField(
                        help_text=b"When the role finishes", verbose_name="end"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_role",
                        to="people.Person",
                    ),
                ),
                (
                    "viewport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.LedgerViewport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="ledger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.Ledger",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role", unique_together=set([("person", "viewport")])
        ),
    ]
