# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("gradebook", "0007_auto_20170315_0954"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Person",
            ),
        )
    ]
