# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:41
from __future__ import unicode_literals

from django.db import migrations


def forward_data(apps, schema_editor):
    """
    Data migration - populate score.person from score.student_registration.student.person
    """
    Score = apps.get_model("gradebook", "Score")
    for score in Score.objects.all():
        score.person = score.student_registration.student.person
        score.save()


def backward_data(apps, schema_editor):
    """
    Reverse data migration; not actually implemented.
    """


class Migration(migrations.Migration):

    dependencies = [("gradebook", "0008_score_person")]

    operations = [migrations.RunPython(forward_data, backward_data)]
