# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 15:50
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gradebook", "0010_auto_20170406_1005")]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="applies_to",
            field=models.SlugField(
                blank=True,
                help_text="A slug for which this formula may apply, leave blank for any",
            ),
        ),
        migrations.AlterField(
            model_name="formula",
            name="args",
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
