# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:20
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("gradebook", "0012_auto_20170424_1113"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="score", options={"ordering": ("person", "task")}
        ),
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                help_text="The url fragment for accessing this task (must be unique for this section)",
                max_length=64,
                populate_from=b"name",
                unique_with=(b"ledger",),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="score", unique_together=set([("task", "person")])
        ),
        migrations.AlterUniqueTogether(
            name="task", unique_together=set([("slug", "ledger")])
        ),
    ]
