# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 14:49
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gradebook", "0014_auto_20170424_1125")]

    operations = [
        migrations.AlterField(
            model_name="ledgerviewport",
            name="tasks",
            field=models.ManyToManyField(blank=True, to="gradebook.Task"),
        ),
        migrations.AlterField(
            model_name="score",
            name="public",
            field=models.NullBooleanField(
                choices=[
                    (None, "Use task setting"),
                    (False, "Hide from student"),
                    (True, "Show to student"),
                ],
                help_text="Whether or not students can see their own score",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="public",
            field=models.NullBooleanField(
                choices=[
                    (None, "Use category setting"),
                    (False, "Hide from students"),
                    (True, "Show to students"),
                ],
                help_text="Whether or not students can see their own score",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=64,
                populate_from="name",
                unique_with=("ledger",),
            ),
        ),
    ]
