# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("gradebook", "0016_auto_20170529_1415")]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "base_manager_name": "objects",
                "ordering": ("ordering", "name"),
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="formula", options={"base_manager_name": "objects"}
        ),
        migrations.AlterModelOptions(
            name="ledger",
            options={"base_manager_name": "objects", "ordering": ("ordering", "name")},
        ),
        migrations.AlterModelOptions(
            name="ledgerviewport",
            options={"base_manager_name": "objects", "ordering": ("ordering", "name")},
        ),
        migrations.AlterModelOptions(
            name="response", options={"base_manager_name": "objects"}
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "base_manager_name": "objects",
                "ordering": ("viewport", "person"),
            },
        ),
        migrations.AlterModelOptions(
            name="score",
            options={"base_manager_name": "objects", "ordering": ("person", "task")},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "base_manager_name": "objects",
                "ordering": ("ordering", "category", "name"),
            },
        ),
    ]
