# Generated by Django 2.0 on 2017-12-08 17:14

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gradebook", "0017_auto_20170602_0806")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                max_length=64,
                populate_from="name",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="formula",
            name="applies_to",
            field=models.SlugField(
                blank=True,
                default="-dont-show-",
                help_text="A slug for which this formula may apply, leave blank for any",
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="dtend",
            field=models.DateTimeField(
                help_text="When the ledger finishes", verbose_name="end"
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="dtstart",
            field=models.DateTimeField(
                help_text="When the ledger begins", verbose_name="start"
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=128, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="ledgerviewport",
            name="ledger",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.Ledger",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerviewport",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=128, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="task",
            field=models.ForeignKey(
                help_text="An associated task, if one can be determined",
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.Task",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="viewport",
            field=models.ForeignKey(
                help_text="An associated viewport, if appropriate",
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.LedgerViewport",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="dtend",
            field=models.DateTimeField(
                help_text="When the role finishes", verbose_name="end"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="dtstart",
            field=models.DateTimeField(
                help_text="When the role begins", verbose_name="start"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[
                    ("su", "Superuser"),
                    ("co", "Course Coordinator"),
                    ("in", "Instructor"),
                    ("ta", "Teaching Assistant"),
                    ("mk", "Marker"),
                    ("ld", "Lab Demonstrator"),
                    ("ob", "Observer"),
                    ("st", "Student"),
                ],
                default="st",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"active": True},
                related_name="reverse_dependencies",
                to="gradebook.Score",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="formula",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.Formula",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="person",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="task",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.Task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.Category",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="formula",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.Formula",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="ledger",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.Ledger",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                max_length=64,
                populate_from="name",
                unique_with=("ledger",),
            ),
        ),
    ]
